name: invest_portfolio
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  grpc: ^4.1.0
  protobuf: ^4.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  fl_chart: ^0.71.0
  fixnum: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  protoc_plugin: ^22.4.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
